profile:
  path: /{_locale}/user/profile
  controller: App\Controller\UserController::profile
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

user_edit:
  path: /{_locale}/user/edit
  controller: App\Controller\UserController::edit
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

user_settings:
  path: /{_locale}/user/settings
  controller: App\Controller\UserController::settings
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

user_show:
  path: /{_locale}/user/{usernameCanonical}
  controller: App\Controller\UserController::show
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'

user_tree_show:
  path: /{_locale}/my-tree
  controller: App\Controller\UserController::treeShow
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'